/*
 * Each term in the Fibonaci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
#include <stdio.h>

#define MAX_VAL 4e6
int main(void){
    int fib_val_1 = 1,
        fib_val_2 = 2,
        fib_val_next = fib_val_1 + fib_val_2;

    int sum = fib_val_2;
    
    while(fib_val_next < MAX_VAL){
        fib_val_1 = fib_val_2;
        fib_val_2 = fib_val_next;
        if(!(fib_val_next % 2))
            sum += fib_val_next;

        fib_val_next = fib_val_1 + fib_val_2;
    }

    printf("%i\n", sum);
    return 0;
};
