/*
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 
 * 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *   1, 3, 6, 10, 15, 21, 28, 36, 45, 55,...
 * Let us list the factors of the first seven triangle numbers:
 *    1: 1
 *    3: 1, 3
 *    6: 1, 2, 3, 6
 *   10: 1, 2, 5, 10
 *   15: 1, 3, 5, 15
 *   21: 1, 3, 7, 21
 *   28: 1, 2, 4, 7, 14, 28
 * We can see that 28 is the first triangle number to have over five divisors.
 * What is the value of the first triangle number to have over five hundred divisors?
 */
#include <stdio.h>
#include "tools.h"

int main(void){
    int i = 0;
    int sum = 0;
    int save = 0;
    while(save < 500){
        i += 1;
        sum += i;
        save = count_divisors(sum);
        //if(!(i % 100))
        //    printf("%i %i %i\n", i, sum, save);
    }

    printf("%i\n", sum);
    return 0;
};
